// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Complete localization for deep cleaning, large files finder, duplicate files & photos,
/// and macOS fluidity & health optimization across all 13 supported languages.
struct CleanerExtendedStrings {
    let tabSystemJunk: String
    let tabLargeFiles: String
    let tabDuplicates: String
    let tabOptimizer: String

    let catBrowserCaches: String
    let catAppMediaCaches: String
    let catSystemLogs: String
    let catTemporaryResidue: String
    let catExternalTrashes: String

    let browserCachesCaption: String
    let appMediaCachesCaption: String
    let systemLogsCaption: String
    let temporaryResidueCaption: String
    let externalTrashesCaption: String

    static func localized(_ language: AppLanguage) -> CleanerExtendedStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .es: return .es
        case .fr: return .fr
        case .de: return .de
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .ru: return .ru
        case .tr: return .tr
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension CleanerExtendedStrings {
    static let enUS = CleanerExtendedStrings(
        tabSystemJunk: "System Junk",
        tabLargeFiles: "Large Files",
        tabDuplicates: "Duplicates & Photos",
        tabOptimizer: "macOS Advisor",
        catBrowserCaches: "Browser Caches",
        catAppMediaCaches: "Communication & Media",
        catSystemLogs: "System Diagnostics",
        catTemporaryResidue: "Temporary Residue",
        catExternalTrashes: "External Drive Trashes",
        browserCachesCaption: "Web caches and service workers created by browsers.",
        appMediaCachesCaption: "Caches created by communication and media streaming applications.",
        systemLogsCaption: "Diagnostic and crash reports generated by macOS and background daemons.",
        temporaryResidueCaption: "Stale incomplete downloads and temporary cache remnants.",
        externalTrashesCaption: "Trashes located on connected external volumes."
    )

    static let ptBR = CleanerExtendedStrings(
        tabSystemJunk: "Lixo do Sistema",
        tabLargeFiles: "Arquivos Grandes",
        tabDuplicates: "Duplicatas e Fotos",
        tabOptimizer: "Fluidez e Otimização",
        catBrowserCaches: "Caches de Navegadores",
        catAppMediaCaches: "Comunicação e Mídia",
        catSystemLogs: "Diagnósticos do Sistema",
        catTemporaryResidue: "Resíduos Temporários",
        catExternalTrashes: "Lixeiras de Discos Externos",
        browserCachesCaption: "Caches de navegação e service workers criados por navegadores.",
        appMediaCachesCaption: "Caches criados por aplicativos de comunicação e streaming de mídia.",
        systemLogsCaption: "Relatórios de falhas e diagnósticos gerados pelo sistema e daemons.",
        temporaryResidueCaption: "Downloads antigos incompletos e sobras de arquivos temporários.",
        externalTrashesCaption: "Lixeiras presentes em discos e volumes externos conectados."
    )

    static let es = CleanerExtendedStrings(
        tabSystemJunk: "Basura del sistema",
        tabLargeFiles: "Archivos grandes",
        tabDuplicates: "Duplicados y fotos",
        tabOptimizer: "Optimización macOS",
        catBrowserCaches: "Cachés de navegadores",
        catAppMediaCaches: "Comunicación y multimedia",
        catSystemLogs: "Diagnósticos del sistema",
        catTemporaryResidue: "Residuos temporales",
        catExternalTrashes: "Papeleras de discos externos",
        browserCachesCaption: "Cachés web y service workers creados por navegadores.",
        appMediaCachesCaption: "Cachés creados por aplicaciones de mensajería y streaming.",
        systemLogsCaption: "Informes de diagnóstico y errores generados por macOS.",
        temporaryResidueCaption: "Descargas incompletas antiguas y archivos temporales residuales.",
        externalTrashesCaption: "Papeleras ubicadas en unidades externas conectadas."
    )

    static let fr = CleanerExtendedStrings(
        tabSystemJunk: "Fichiers inutiles",
        tabLargeFiles: "Fichiers volumineux",
        tabDuplicates: "Doublons et photos",
        tabOptimizer: "Optimisation macOS",
        catBrowserCaches: "Caches des navigateurs",
        catAppMediaCaches: "Communication et médias",
        catSystemLogs: "Diagnostics du système",
        catTemporaryResidue: "Résidus temporaires",
        catExternalTrashes: "Corbeilles des disques externes",
        browserCachesCaption: "Caches web et service workers créés par les navigateurs.",
        appMediaCachesCaption: "Caches créés par les applications de messagerie et de streaming.",
        systemLogsCaption: "Rapports de diagnostic et plantages générés par macOS.",
        temporaryResidueCaption: "Téléchargements incomplets anciens et résidus temporaires.",
        externalTrashesCaption: "Corbeilles situées sur les volumes externes connectés."
    )

    static let de = CleanerExtendedStrings(
        tabSystemJunk: "Systemmüll",
        tabLargeFiles: "Große Dateien",
        tabDuplicates: "Duplikate & Fotos",
        tabOptimizer: "macOS-Optimierung",
        catBrowserCaches: "Browser-Caches",
        catAppMediaCaches: "Kommunikation & Medien",
        catSystemLogs: "Systemdiagnoseberichte",
        catTemporaryResidue: "Temporäre Rückstände",
        catExternalTrashes: "Papierkörbe externer Laufwerke",
        browserCachesCaption: "Web-Caches und Service-Worker von Browsern.",
        appMediaCachesCaption: "Caches von Chat- und Streaming-Apps.",
        systemLogsCaption: "Diagnose- und Absturzberichte von macOS.",
        temporaryResidueCaption: "Alte unvollständige Downloads und temporäre Überreste.",
        externalTrashesCaption: "Papierkörbe auf angeschlossenen externen Laufwerken."
    )

    static let it = CleanerExtendedStrings(
        tabSystemJunk: "File inutili",
        tabLargeFiles: "File grandi",
        tabDuplicates: "Duplicati e foto",
        tabOptimizer: "Ottimizzazione macOS",
        catBrowserCaches: "Cache dei browser",
        catAppMediaCaches: "Comunicazione e media",
        catSystemLogs: "Diagnostica di sistema",
        catTemporaryResidue: "Residui temporanei",
        catExternalTrashes: "Cestini unità esterne",
        browserCachesCaption: "Cache web e service worker creati dai browser.",
        appMediaCachesCaption: "Cache create da app di messaggistica e streaming.",
        systemLogsCaption: "Report di diagnostica e arresti anomali generati da macOS.",
        temporaryResidueCaption: "Download incompleti obsoleti e file temporanei residui.",
        externalTrashesCaption: "Cestini presenti sulle unità esterne collegate."
    )

    static let ja = CleanerExtendedStrings(
        tabSystemJunk: "システムジャンク",
        tabLargeFiles: "大容量ファイル",
        tabDuplicates: "重複ファイルと写真",
        tabOptimizer: "macOS最適化",
        catBrowserCaches: "ブラウザキャッシュ",
        catAppMediaCaches: "通信・メディアキャッシュ",
        catSystemLogs: "システム診断レポート",
        catTemporaryResidue: "一時的な残存ファイル",
        catExternalTrashes: "外付けドライブのゴミ箱",
        browserCachesCaption: "ブラウザが作成したウェブキャッシュとService Worker。",
        appMediaCachesCaption: "メッセージングおよびメディアアプリのキャッシュ。",
        systemLogsCaption: "macOSおよびデーモンが生成したクラッシュレポート。",
        temporaryResidueCaption: "古い未完了ダウンロードと不要な一時ファイル。",
        externalTrashesCaption: "接続された外付けドライブのゴミ箱。"
    )

    static let ko = CleanerExtendedStrings(
        tabSystemJunk: "시스템 정크",
        tabLargeFiles: "대용량 파일",
        tabDuplicates: "중복 파일 및 사진",
        tabOptimizer: "macOS 최적화",
        catBrowserCaches: "브라우저 캐시",
        catAppMediaCaches: "통신 및 미디어 캐시",
        catSystemLogs: "시스템 진단 보고서",
        catTemporaryResidue: "임시 잔여 파일",
        catExternalTrashes: "외장 드라이브 휴지통",
        browserCachesCaption: "웹 브라우저에서 생성된 캐시 및 서비스 워커 데이터.",
        appMediaCachesCaption: "메시징 및 스트리밍 앱에서 생성된 캐시.",
        systemLogsCaption: "macOS에서 생성된 충돌 및 진단 보고서.",
        temporaryResidueCaption: "오래된 불완전 다운로드 및 임시 잔여 파일.",
        externalTrashesCaption: "연결된 외장 드라이브의 휴지통."
    )

    static let ru = CleanerExtendedStrings(
        tabSystemJunk: "Системный мусор",
        tabLargeFiles: "Крупные файлы",
        tabDuplicates: "Дубликаты и фото",
        tabOptimizer: "Оптимизация macOS",
        catBrowserCaches: "Кэш браузеров",
        catAppMediaCaches: "Связь и медиа",
        catSystemLogs: "Системные отчеты",
        catTemporaryResidue: "Временные остатки",
        catExternalTrashes: "Корзины внешних дисков",
        browserCachesCaption: "Веб-кэш и служебные данные браузеров.",
        appMediaCachesCaption: "Кэш приложений для общения и стриминга.",
        systemLogsCaption: "Отчеты об ошибках и диагностические данные macOS.",
        temporaryResidueCaption: "Старые незавершенные загрузки и временные файлы.",
        externalTrashesCaption: "Корзины на подключенных внешних накопителях."
    )

    static let tr = CleanerExtendedStrings(
        tabSystemJunk: "Sistem Çöpü",
        tabLargeFiles: "Büyük Dosyalar",
        tabDuplicates: "Yinelenenler ve Fotoğraflar",
        tabOptimizer: "macOS İyileştirici",
        catBrowserCaches: "Tarayıcı Önbellekleri",
        catAppMediaCaches: "İletişim ve Medya",
        catSystemLogs: "Sistem Tanılama Raporları",
        catTemporaryResidue: "Geçici Kalıntılar",
        catExternalTrashes: "Harici Sürücü Çöp Kutuları",
        browserCachesCaption: "Tarayıcılar tarafından oluşturulan web önbellekleri.",
        appMediaCachesCaption: "İletişim ve medya uygulamaları önbellekleri.",
        systemLogsCaption: "macOS tarafından oluşturulan tanılama ve kilitlenme raporları.",
        temporaryResidueCaption: "Eski tamamlanmamış indirmeler ve geçici artıklar.",
        externalTrashesCaption: "Bağlı harici sürücülerdeki çöp kutuları."
    )

    static let zhHans = CleanerExtendedStrings(
        tabSystemJunk: "系统垃圾",
        tabLargeFiles: "大文件清理",
        tabDuplicates: "重复文件与照片",
        tabOptimizer: "macOS流畅优化",
        catBrowserCaches: "浏览器缓存",
        catAppMediaCaches: "通讯与媒体缓存",
        catSystemLogs: "系统诊断报告",
        catTemporaryResidue: "临时残留文件",
        catExternalTrashes: "外置磁盘废纸篓",
        browserCachesCaption: "浏览器生成的网页缓存及Service Worker。",
        appMediaCachesCaption: "通讯和流媒体软件生成的本地缓存。",
        systemLogsCaption: "macOS及后台进程生成的崩溃与诊断报告。",
        temporaryResidueCaption: "陈旧的未完成下载文件与临时残留。",
        externalTrashesCaption: "已连接外置存储设备中的废纸篓。"
    )

    static let zhTW = CleanerExtendedStrings(
        tabSystemJunk: "系統垃圾",
        tabLargeFiles: "大型檔案清理",
        tabDuplicates: "重複檔案與照片",
        tabOptimizer: "macOS流暢優化",
        catBrowserCaches: "瀏覽器快取",
        catAppMediaCaches: "通訊與媒體快取",
        catSystemLogs: "系統診斷報告",
        catTemporaryResidue: "暫存殘留檔案",
        catExternalTrashes: "外接磁碟垃圾桶",
        browserCachesCaption: "瀏覽器產生的網頁快取及Service Worker。",
        appMediaCachesCaption: "通訊和串流媒體軟體產生的本機快取。",
        systemLogsCaption: "macOS及背景處理程序產生的當機與診斷報告。",
        temporaryResidueCaption: "陳舊的未完成下載檔案與暫存殘留。",
        externalTrashesCaption: "已連接外接儲存裝置中的垃圾桶。"
    )

    static let zhHK = CleanerExtendedStrings(
        tabSystemJunk: "系統垃圾",
        tabLargeFiles: "大型檔案清理",
        tabDuplicates: "重複檔案與相片",
        tabOptimizer: "macOS流暢優化",
        catBrowserCaches: "瀏覽器快取",
        catAppMediaCaches: "通訊與媒體快取",
        catSystemLogs: "系統診斷報告",
        catTemporaryResidue: "暫存殘留檔案",
        catExternalTrashes: "外置磁碟垃圾桶",
        browserCachesCaption: "瀏覽器產生的網頁快取及Service Worker。",
        appMediaCachesCaption: "通訊和串流媒體軟體產生的本機快取。",
        systemLogsCaption: "macOS及後台進程產生的崩潰與診斷報告。",
        temporaryResidueCaption: "陳舊的未完成下載檔案與暫存殘留。",
        externalTrashesCaption: "已連接外置儲存裝置中的垃圾桶。"
    )
}
